name: Addition of new RISC-V tutorial resource
description: A template to request for addition of a new RISC-V tutorial resource to the compiled list of resources
title: "[New RISC-V Tutorial Resource] - ENTER BRIEF RESOURCE TITLE HERE"
labels: 
  - documentation
  - enhancement
assignees:
  - KuthumiPepple
body: |

  ### Documentation Item

  [Provide a brief description of the item you would like to see added to the documentation]

  ### Additional Details

  [Include any additional details or context that might be helpful for the maintainers]

  ### Proposed Solution

  [If you have any suggestions or ideas on how this item should be documented, please include them here]
